### ISSUE TITLE
Unhandled Promise Rejection for ctra init

### ISSUE THREAD

**Issue by mathiasmah** [CantaraJS/cantara#13]
When running 'ctra init <projectname>':

> (node:16640) UnhandledPromiseRejectionWarning: [object Array]
(node:16640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by scriptify** [comment]
Should be fixed in 0.0.7
