### ISSUE TITLE
Build changed should take into acount all commits of that push

### ISSUE THREAD

**Issue by scriptify** [CantaraJS/cantara#24]
Currently, only the commits between the current and the last commit are taken into account for all `*-changed` commands. This is not desirable, because those commands are most likely executed in CI environments, where one push contains more commits. We need to find a way to retrieve a list of all commits within that push. If not possible directly with git, we could also save such a list in the repo itself using a pre commit hook or append it to the commit message.

**Comment by scriptify** [comment]
One possible solution could be to use releases and automatically create a new release when this command is used (using git tags).

**Comment by mathiasmah** [comment]
This could be tricky, locally we could probably achieve this some how with the git history, and comparing local and remote branch. But CI systems often work in a way that between builds it is always a new clone of the project, so we don't have local history.

The issue with creating git tags, is that a release and a build run is not always the same, what if I have feature branches and also want to run builds there? I would have a lot of version tags which are not really new versions.

An option would be to add a hook that, adds a commit message with all commits in this push. But this message would be visible to the users, and it would be better if this is transparent to the user.

**Comment by scriptify** [comment]
We could introduce special tags that are just used by the CI system, e.g. `ci-build{incrementing_counter}`. This way you would always search for the latest tag and include all commits from there on. The only downside is that there would be a lot of not very useful tags in the repo. We could also just use one tag and when running CI, find that tag, delete it, and create a new one for the next run. Pre-push hooks are also a possible solution, instead of appending to the commit message we could create a .cantara folder and add it using `amend` before each commit. But this would require to use some additional tools like husky...

**Comment by mathiasmah** [comment]
A single special tag that is moved after each build, could be feasible. But there is still a tag per branch needed I think, and what if I want to run the build locally as well? Does it still work?

A .cantara folder where information like this is hold, is probably the most flexible solution.

**Comment by scriptify** [comment]
We could create a such a tag for each branch, and let Cantara figure out the tag according to the current branch. But yeah, saving it as a file would be the better solution, less "hacky".
