### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by mathiasmah** [CantaraJS/cantara#27]
When the command "ctra new react-component <component>" is executed and there is no "packages" folder in the project, the fallowing error occurs: 

[
  [Error: ENOENT: no such file or directory, mkdir '/path/to/project/packages/component'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'mkdir',
    path: '/path/to/project/packages/component'
  }
]

Infos:
OS: Linux, Ubuntu 19.04

**Comment by scriptify** [comment]
Should be fixed in v0.4.1

**Comment by Krishna9100** [comment]
push an existing repository from the command line, you have to make branch
git remote add origin https://github.com/Krishna9100/food-website.git
git branch -M main
git push -u origin main
