### ISSUE TITLE
Cloning the start template failing in directory that has a space in its name

### ISSUE THREAD

**Issue by Pjaerr** [CantaraJS/cantara#29]
**Describe the bug**
When running the `cantara init` command. I can provide the name of the directory, and then I choose the starter template, it tries to clone the template to the file path I am in but the file path contains a space in the name so it fails citing `Fatal: Too many arguments`. This functionality works as expectecd when cloning to a directory without any spaces.

**To Reproduce**
1. Run `cantara init` in a directory that has a space in the name EG: `C:/Desktop/Code Playground/Projects`

2. After naming your project, choose the default starter template by pressing Enter.

**Expected behavior**
I expected the project to be created. This works on directories without a space in the name.

**Screenshots**
![image](https://user-images.githubusercontent.com/11336751/79429154-11a92400-7fbf-11ea-945b-59ecca5f568b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 10.0.18362 Build 18362

**Comment by scriptify** [comment]
Should be fixed in version 1.4.2:
https://github.com/CantaraJS/cantara/commit/b410ed7b54f362bc8f9a7bf231c988a090531b70

Thanks for the hint!
