### ISSUE TITLE
Pre-Push Hook breaks git history 

### ISSUE THREAD

**Issue by mathiasmah** [CantaraJS/cantara#37]
**Describe the bug**
The pre-push hook creates a diversion between the local and the remote branch, with two different commit hashes. This means after each push I have to perform a merge commit or a hard reset. 

**To Reproduce**
Push changes to the remote

**Expected behavior**
After a push the remote and local branch shoud be in the same state

**Screenshots**
![grafik](https://user-images.githubusercontent.com/15261743/81393730-20e44300-9121-11ea-9acd-2de12df11d67.png)

**Desktop**
 - OS: Windows 10
 - Version: v1.6.0

**Additional context**
According to [Stackoverflow](https://stackoverflow.com/questions/21334493/git-commit-in-pre-push-hook) this is because the git compiles the changes to be pushed, before invoking the pre-push-hook.

**Comment by scriptify** [comment]
I think we should just use a pre-commit hook instead

**Comment by mathiasmah** [comment]
I changed it from pre-push hook to pre-commit hook.
This solves the problem described above and I also could provide a PR.

However
