### ISSUE TITLE
Possibility to extend webpack and babel config

### ISSUE THREAD

**Issue by scriptify** [CantaraJS/cantara#49]
Sometimes it is needed to modify the webpack or babel config on a project per project basis, without adding those modifications to Cantara itself.

To makes this possible, we could implement a system which allows for modifying the used webpack and babel configs though user defined files.

Those files, `webpack.config.js` and `babel.config.js` should export a function, which gets passed the current config as the first parameter and a merge utility function as a second paramater. It should return the modified config.

We have 2 options wherer those files can be created:
- In each app/package separately
- At the root of the project

If defined at the root of the project, there must be a way to tell the different config types apart, which could be passed in as a third parameter (e.g. React app webpack config, serverless webpack config, etc).

I would not support both options.

Either way, those functions need then be invoked in the `build` or `dev` scripts before the config is passed to webpack. For serverless, this must happen during the `prepare` step, as those webpack configs are pre-generated.

@mathiasmah

**Comment by mathiasmah** [comment]
Same should be possible for jest configuration.
