### ISSUE TITLE
Do not bundle CommonJS packages when building

### ISSUE THREAD

**Issue by scriptify** [CantaraJS/cantara#50]
Currently, when building packages, webpack is used to transpile and bundle CommonJS builds. Bundling makes sense to produce UMD builds, for direct usage via CDNs ecc., but not so much for CommonJS builds, as that code is published to NPM and then most likely consumed in an environment where a bundler is present. Therefore, I'd suggest to skip the bundling (webpack) step for libraries, when building, altogether: Just use `babel` for transpiling and `tsc` for type generation directly. 

The only thing which can become problematic here, is the fact that also all of the rest we do through webpack plugins isn't done anymore, e.g. inlining CSS. But this shouldn't be a problem, as long as the target environment supports that (for example requiring CSS or Webworkers or whatever). 

@mathiasmah

**Comment by mathiasmah** [comment]
Resolved by #52
