### ISSUE TITLE
Link external Cantara packages for development

### ISSUE THREAD

**Issue by mathiasmah** [CantaraJS/cantara#58]

**Comment by scriptify** [comment]
When developing an application, it sometimes occurs that you installed packages from another Cantara project you own. In that case, changes to the code of that package would be immediately reflected as if it was local code. This way, the external package can be tested in other contexts.

From a DX perspective, let's just imitate the way YARN/NPM do it:
Execting `cantara link <package-name>` in the external repo and `cantara link add <package-name>` (or the likes) locally links an external package.

Implementation-wise, the main difficulties I see here are:
- Correctly linking all package dependencies
- Compiling the external code the same way as the local code (Webpack needs to be tweaked accordingly)

I will first evaluate the different routes we can take (file-based, symlink-based, etc.), but we can certainly learn a lot from libs like [yalc](https://github.com/wclr/yalc)

**Comment by mathiasmah** [comment]
Sounds good. 
Since we don't want to change the package.json on linking, as most of the other tools do, I would suggest to log all linked packages currently used, at `ctra build/dev`. This way the user has a better overview. 
At `ctra build` this could even be a warning, since we most likely don't want to use linked packages for a production build.
